#!/usr/bin/env ruby

require 'optimist'
require 'gpe/gcc/pricing/azure'

=begin

    Pull Azure and AWS pricing and put the resulting files in the output directory
    pointed to by the --output | -o specification.

    AWS
    
        Permissions are assumed to be on the local file system for
        the user running this.

    Azure
    
        Permissions for the sku file are emmbedded.
        The pricing file is public. There is no authentication needed.

=end


include GPE::GCC::Pricing::Azure

module GPE; module GCC; module Pricing
    
    Log = Logger.new(STDOUT)

    OPTS = Optimist::options do
        opt :output, "Output Directory", :type => :string, :default => '.', :required => true
    end
    
    output_dir = OPTS[:output]
    
    # azure_collect_and_build(output_dir)
    aws_connect_and_build(output_dir)

end; end; end