#!/usr/bin/env ruby

require 'optimist'
require 'gpe/gcc/base'

=begin

    Pull Azure and AWS pricing and put the resulting files in the output directory
    pointed to by the --output | -o specification.

    AWS
    
        Permissions are assumed to be on the local file system for
        the user running this.

    Azure
    
        Permissions for the sku file are emmbedded.
        The pricing file is public. There is no authentication needed.

=end

include GPE::GCC::Pricing::Azure
include GPE::GCC::Pricing::AWS

module GPE; module GCC; module Pricing
    
    Log = Logger.new(STDOUT)

    OPTS = Optimist::options do
        opt :output, "Output Directory", :type => :string, :default => 'gcc'
    end
    
    # Set output dir if it exists create cache under it.
    output_dir = OPTS[:output]    
    if File.exist?(output_dir)
        FileUtils.mkdir_p("#{output_dir}/cache")
    else
        Log.error("Output directory does not exist.")
        exit 1
    end

    Log.info("Collect and build Azure pricing files...")
    azure_collect_and_build(output_dir)
    
    Log.info("Collect and build AWS pricing files...")
    aws_collect_and_build(output_dir)

end; end; end